apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-sa
